cache:
  paths:
    - /home/fabricasoft/.rvm/gems/ruby-2.4.0@bebras-api/gems/

build:
  before_script:
    - pwd
    - cat .ruby-version
    - source /etc/profile.d/rvm.sh
    - rvm automount
    - rvm gemset use bebras-api
    - bundle
    - echo "Done build"
  script:
    - rspec
