cache:
  paths:
    - /home/fabricasoft/.rvm/gems/ruby-2.4.0@bebras-api/gems/

build:
  before_script:
    - apt-get install ruby 2.4.1
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - bundle install --quiet
    - bundle exec rake db:migrate --quiet
    - bundle exec rake db:test:prepare --quiet

  script:
    - rspec
