cache:
  paths:
    - /home/fabricasoft/.rvm/gems/ruby-2.4.0@bebras-api/gems/

# build:
#   before_script:
#     - pwd
#     # - rvm automount
#     - rvm gemset use bebras-api
#     - bundle
#     - echo "Done build"
#   script:
#     - rspec
build:
  before_script:
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec