cache:
  paths:
    - /home/fabricasoft/.rvm/gems/ruby-2.4.0@bebras-api/gems/

build:
  before_script:
    - pwd
    - echo "2.4.0" > .ruby-version
    - echo "bebras-br-pc" > .ruby-gemset
    - source /etc/profile.d/rvm.sh
    - cd .
    - gem install bundle
    - bundle
    - echo "Done build"
  script:
    - rspec
