cache:
  paths:
    - /home/fabricasoft/.rvm/gems/ruby-2.4.0@bebras-api/gems/

build:
  before_script:
    - source /etc/profile
    - pwd
    - rvm gemset use bebras-api
    - bundle
    - echo "Done build"
  script:
    - rspec
