default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: root
development:
  <<: *default
  database: bebras_api_dev
# production:
#     url: <%= ENV['DATABASE_URL'] %>
# test:
#   <<: *default
#   database: avisei_api_test